[render]
font = "local:NotoSans-Regular"

[source]
path = "keymap.c"
hscale = 7
vscale = 2

[remap]
"C|Esc" = "Ctrl·Esc"
"S|Entr" = "S·Enter"
"Nav|;" = "Nav · ;"
"Reset" = "Rst"
"Debug" = "Dbg"
"Qwerty" = "Qwr"
"AudOn" = "Aud\nON"
"AudOff" = "Aud\nOFF"
"AGnorm" = "AG\nnorm"
"AGswap" = "AG\nswap"
"Voice-" = "VO\n-"
"Voice+" = "VO\n+"
"MusOn" = "Mus\nON"
"MusOff" = "Mus\nOFF"
"MidiOn" = "Midi\nON"
"MidOff" = "Midi\nOFF"

[[fontmap]]
font = "local:DejavuSans"
labels = [ "↑", "←", "↓", "→" ]

[keycolor]
"Ctrl·Esc" = "#ffac54"
"Lower" = "#ffac54"
"Raise" = "#c260ff"
"S·Enter" = "#c260ff"
"Accent" = "#99ed97"
"Nav · ;" = "#12e8c4"

[[label]]
position = "center"
layer = "Prog"

[[label]]
position = "top"
scale = 0.8
layer = "Raise"
color = "#8700db"

[[label]]
position = "bottom"
scale = 0.8
layer = "Lower"
color = "#db7100"

[[label]]
position = "top-right"
scale = 0.5
layer = "Navigation"
color = "#6ad8c6"
ignore = [ "Shift", "Ctrl" ]

[[label]]
position = "left"
scale = 0.8
layer = "Accent"
color = "#036001"
ignore = [ "Shift" ]

[[label]]
position = "bottom-right"
scale = 0.5
layer = "Adjust (Lower + Raise)"
ignore = [ "Del" ]
